#include <iostream>
#include <string>
#include <fstream>
#include <istream>
#include <sstream>
#include <unordered_map>
#include <set>
#include <string>
#include "../src/ahocorasick.cpp"
#include "../includes/fasta_reader.h"
#include "../includes/csv_file.h"
#include <boost/algorithm/string.hpp>
//#includes <boost/asio/impl/src.hpp>